# Generated by Django 4.1.1 on 2022-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_client_dni_client_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
