# Generated by Django 4.1.1 on 2022-09-12 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_alter_employee_date_joined_employee_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 9, 12, 23, 29, 23, 841479, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
