# Generated by Django 4.1.1 on 2022-10-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category_date_create_category_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
